//
//  CreationPresenter.swift
//  mobilka
//
//  Created by Андрей Лихачев on 03.12.2019.
//  Copyright (c) 2019 Андрей Лихачев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreationPresentationLogic
{
  func contactAdded()
}

class CreationPresenter: CreationPresentationLogic
{
  weak var viewController: CreationDisplayLogic?
  
  // MARK: Do something
  
  func contactAdded()
  {
    viewController?.contactAdded()
  }
}
