//
//  CreationWorker.swift
//  mobilka
//
//  Created by Андрей Лихачев on 03.12.2019.
//  Copyright (c) 2019 Андрей Лихачев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FirebaseAuth
import Firebase

class CreationWorker
{
    let db = Firestore.firestore()
    
    func createContact(response: Creation.Models.Contact, onSuccess: (() -> Void)?){
        var ref: DocumentReference? = nil
        ref = db.collection("contacts").addDocument(data: [
            "family_name": response.familyName,
            "first_name": response.name,
            "last_name": response.lastName,
            "phone": response.phone,
            "e-mail": response.email,
        ]) { err in
            if let err = err {
                print("Error adding document: \(err)")
            } else {
                onSuccess?()
            }
        }
  }
}
