//
//  CreationInteractor.swift
//  mobilka
//
//  Created by Андрей Лихачев on 03.12.2019.
//  Copyright (c) 2019 Андрей Лихачев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreationBusinessLogic
{
  func doSomething(request: Creation.Models.Contact)
}

protocol CreationDataStore
{
  //var name: String { get set }
}

class CreationInteractor: CreationBusinessLogic, CreationDataStore
{
  var presenter: CreationPresentationLogic?
  var worker: CreationWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Creation.Models.Contact)
  {
    worker = CreationWorker()
    worker?.createContact(response: request, onSuccess: {
        self.presenter?.contactAdded()
    })
  }
}
