//
//  CreationModels.swift
//  mobilka
//
//  Created by Андрей Лихачев on 03.12.2019.
//  Copyright (c) 2019 Андрей Лихачев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Creation
{
  // MARK: Use cases
  
  enum Models
  {
    struct Contact
    {
        let familyName: String
        let name: String
        let lastName: String
        let phone: String
        let email: String
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
