//
//  MapModels.swift
//  mobilka
//
//  Created by Андрей Лихачев on 03.12.2019.
//  Copyright (c) 2019 Андрей Лихачев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

enum Map
{
    // MARK: Use cases
    
    enum Models
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct City
        {
            let id: Int
            let name: String
            let lat: Double
            let lon: Double
            let temp: Double
            let icon: String
            let dt: Int
        }
    }
    
    struct Coordinates{
        let topleft: CLLocationCoordinate2D
        let topright: CLLocationCoordinate2D
        let bottomright: CLLocationCoordinate2D
        let bottomleft: CLLocationCoordinate2D
        
        static func initWithMapView(map: MKMapView) -> Coordinates {
            let rectangle = Coordinates(topleft: MKMapPoint(x: map.visibleMapRect.minX, y: map.visibleMapRect.minY).coordinate, topright: MKMapPoint(x: map.visibleMapRect.maxX, y: map.visibleMapRect.minY).coordinate, bottomright: MKMapPoint(x: map.visibleMapRect.maxX, y: map.visibleMapRect.maxY).coordinate, bottomleft: MKMapPoint(x: map.visibleMapRect.minX, y: map.visibleMapRect.maxY).coordinate)
    
            return rectangle
        }
    }
}
