//
//  ConfigTableModels.swift
//  mobilka
//
//  Created by Илья Ляшенко on 15.10.2019.
//  Copyright (c) 2019 Андрей Лихачев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ConfigTable
{
  // MARK: Use cases
  
  enum DeviceInfo
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
        let keys = ["Name", "Model", "System", "Ver."]
        let info = [UIDevice.current.name, UIDevice.current.model, UIDevice.current.systemName, UIDevice.current.systemVersion]
    }
  }
}
