//
//  ConfigTableInteractor.swift
//  mobilka
//
//  Created by Илья Ляшенко on 15.10.2019.
//  Copyright (c) 2019 Андрей Лихачев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConfigTableBusinessLogic
{
  func doSomething(request: ConfigTable.DeviceInfo.Request)
}

protocol ConfigTableDataStore
{
  //var name: String { get set }
}

class ConfigTableInteractor: ConfigTableBusinessLogic, ConfigTableDataStore
{
  var presenter: ConfigTablePresentationLogic?
  var worker: ConfigTableWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ConfigTable.DeviceInfo.Request)
  {
    worker = ConfigTableWorker()
    worker?.doSomeWork()
    
    let response = ConfigTable.DeviceInfo.Response()
    presenter?.presentSomething(response: response)
  }
}
