//
//  LoginWorker.swift
//  mobilka
//
//  Created by Андрей Лихачев on 10/10/2019.
//  Copyright (c) 2019 Андрей Лихачев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
  func doSomeWork()
  {
  }
}
