//
//  LoginModels.swift
//  mobilka
//
//  Created by Андрей Лихачев on 10/10/2019.
//  Copyright (c) 2019 Андрей Лихачев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum userInfo
  {
    struct Request
    {
        let email: String
        let password: String
        
        init(email: String, password: String) {
            self.email = email
            self.password = password
        }
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
