//
//  WebViewPresenter.swift
//  mobilka
//
//  Created by Ac Lo on 23/10/2019.
//  Copyright (c) 2019 Андрей Лихачев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebViewPresentationLogic
{
  func presentSomething(response: WebView.Something.Response)
}

class WebViewPresenter: WebViewPresentationLogic
{
  weak var viewController: WebViewDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: WebView.Something.Response)
  {
    let viewModel = WebView.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
